// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnoaVMoFku5N_cDcgFIumu3AvMWBebyys',
    appId: '1:811255419240:web:11063266902d5acd93c6dd',
    messagingSenderId: '811255419240',
    projectId: 'hemelvaartbingo',
    authDomain: 'hemelvaartbingo.firebaseapp.com',
    storageBucket: 'hemelvaartbingo.firebasestorage.app',
    measurementId: 'G-F3KJ3V7QZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH26yL25q-2sw8KN3bz5fpzDxy5Oo5nCk',
    appId: '1:811255419240:android:cd1ee220be885e8a93c6dd',
    messagingSenderId: '811255419240',
    projectId: 'hemelvaartbingo',
    storageBucket: 'hemelvaartbingo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrgnfY6jBs0EoTj-B75AQgyveyZVWGOs',
    appId: '1:811255419240:ios:7e018449bf47ef8293c6dd',
    messagingSenderId: '811255419240',
    projectId: 'hemelvaartbingo',
    storageBucket: 'hemelvaartbingo.firebasestorage.app',
    iosBundleId: 'com.kroonen.hemelvaartbingo',
  );
}
